name: Add Chart Promotion

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: 'Name of the chart to upsert'
        type: string
        required: true
      repository:
        description: 'Name of the repository to upsert the chart to'
        type: string
        required: true
      version:
        description: 'Version of the chart (eg. 1.0.0)'
        type: string
        required: true
      release_channel:
        description: 'The release channel the chart version was promoted to'
        type: string
        required: true
      promoted_at:
        description: 'The date and time the chart version was promoted (ISO 8601 format)'
        type: string

concurrency:
  group: update-db-${{ github.ref }}

run-name: Add Chart Promotion (${{ github.event.inputs.repository }}/${{ github.event.inputs.chart_name }}:${{ github.event.inputs.version }}->${{ github.event.inputs.release_channel }})

jobs:
  upsert-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build CLI
        run: ./scripts/build-cli.sh

      - name: Execute CLI
        run: |
          ./tmp/nic-chg -add-chart-promotion='{
            "chart_name": "${{ github.event.inputs.chart_name }}",
            "repository": "${{ github.event.inputs.repository }}",
            "version": "${{ github.event.inputs.version }}",
            "release_channel": "${{ github.event.inputs.release_channel }}",
            "promoted_at": "${{ github.event.inputs.promoted_at }}"
          }'

      - name: Commit data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add db/changelog.db
          git commit -am "[add-chart-promotion] ${{ github.event.inputs.repository }}/${{ github.event.inputs.chart_name }}:${{ github.event.inputs.version }}->${{ github.event.inputs.release_channel }}"
          git push
