name: Build And Test CLI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'db/changelog.db'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'db/changelog.db'

jobs:
  build-and-test-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build CLI
        run: ./scripts/build-cli.sh

      - name: Execute go unit tests
        run: go test -v ./...

      - name: Test CLI
        run: ./scripts/test-cli.sh
