name: Upsert Chart

on:
  workflow_dispatch:
    inputs:
      chart_name:
        description: 'Name of the chart to upsert'
        type: string
        required: true
      repository:
        description: 'Name of the repository to upsert the chart to'
        type: string
        required: true
      line_of_business:
        description: 'Line of business for the chart'
        type: string
      registry_path:
        description: 'Path to the chart in the registry'
        type: string

concurrency:
  group: update-db-${{ github.ref }}

run-name: Upsert Chart (${{ github.event.inputs.repository }}/${{ github.event.inputs.chart_name }})

jobs:
  upsert-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build CLI
        run: ./scripts/build-cli.sh

      - name: Execute CLI
        run: |
          ./tmp/nic-chg -upsert-chart='{
            "chart_name": "${{ github.event.inputs.chart_name }}",
            "repository": "${{ github.event.inputs.repository }}",
            "line_of_business": "${{ github.event.inputs.line_of_business }}",
            "registry_path": "${{ github.event.inputs.registry_path }}"
          }'

      - name: Commit data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add db/changelog.db
          git commit -am "[upsert-chart] ${{ github.event.inputs.repository }}/${{ github.event.inputs.chart_name }}"
          git push
